package com.daralshifa.util;




//import com.sun.jersey.core.util.Base64;
import org.springframework.security.crypto.codec.Base64;

import java.io.File;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Properties;

import javax.activation.DataHandler;
import javax.activation.DataSource;
import javax.activation.FileDataSource;
import javax.mail.BodyPart;
import javax.mail.Message;
import javax.mail.MessagingException;
import javax.mail.Multipart;
import javax.mail.Session;
import javax.mail.Transport;
import javax.mail.internet.InternetAddress;
import javax.mail.internet.MimeBodyPart;
import javax.mail.internet.MimeMessage;
import javax.mail.internet.MimeMultipart;
import javax.mail.util.ByteArrayDataSource;



/**
 *
 * @author melsonbati
 */

public class DashMailer {

    private static DashMailer instance;

    public static  DashMailer getInstance(){
        if(instance ==null)
            instance = new DashMailer();
        return instance;
    }

    private DashMailer(){

    }

    public void sendMail(String from,List<String> toList ,List<String> ccList, String subject ,String body) throws MessagingException{
        Properties props = new Properties();

        //     exchange01.daralshifa.com
        props.put("mail.smtp.host", "mail.daralshifa.com");
        //props.put("mail.smtp.host", "exchange.daralshifa.com");//
        props.put("mail.smtp.user", "ithelpdesk");
        props.put("mail.smtp.password", "it1234"); //mail.smtp.ssl.enable
        props.put("mail.smtp.ssl.enable", "false");
        Session session = Session.getDefaultInstance(props, null);
        session.setDebug(true);
        Message msg = new MimeMessage(session);
        msg.setFrom(new InternetAddress(from));
        InternetAddress ia=null;
        List<InternetAddress> addresees=new ArrayList<InternetAddress>();
        for(String to :toList ){
            ia=new InternetAddress(to);
            addresees.add(ia);
        }
        InternetAddress[] array = new InternetAddress[addresees.size()];
        array=addresees.toArray(array);

        msg.setRecipients(Message.RecipientType.TO,array);

        if(ccList!=null&& ccList.size()>0){

            InternetAddress ia2=null;
            List<InternetAddress> addresees2=new ArrayList<InternetAddress>();
            for(String to :ccList ){
                ia2=new InternetAddress(to);
                addresees2.add(ia2);
            }
            InternetAddress[] array2 = new InternetAddress[addresees2.size()];
            array2=addresees2.toArray(array2);

            msg.setRecipients(Message.RecipientType.CC,array2);
        }
        msg.setSubject(subject);
        msg.setText(body);

        Transport.send(msg);
    }
    public static void sendMail(String from,String to, String subject ,String body) throws MessagingException{
        Properties props = new Properties();
        props.put("mail.smtp.host", "exchange.daralshifa.com");//
        props.put("mail.smtp.user", "ithelpdesk");
        props.put("mail.smtp.password", "it1234"); //mail.smtp.ssl.enable
        props.put("mail.smtp.ssl.enable", "false");
        Session session = Session.getDefaultInstance(props, null);
        session.setDebug(true);
        Message msg = new MimeMessage(session);
        msg.setFrom(new InternetAddress(from));
        InternetAddress ia=null;
        List<InternetAddress> addresees=new ArrayList<InternetAddress>();

        ia=new InternetAddress(to);
        addresees.add(ia);

        InternetAddress[] array = new InternetAddress[addresees.size()];
        array=addresees.toArray(array);
        //msg.setRecipients(Message.RecipientType.TO, new InternetAddress[]{new InternetAddress("melsonbati@daralshifa.com")});
        msg.setRecipients(Message.RecipientType.TO,array);
        msg.setSubject(subject);
        msg.setText(body);

        Transport.send(msg);
    }



    private String getMimeType(String fileExt){

        if(fileExt == null)
            return null;

        Map<String,String> map  =  new HashMap<String,String>();


        map.put(".x3d","application/vnd.hzn-3d-crossword");
        map.put(".3gp","video/3gpp");
        map.put(".3g2","video/3gpp2");
        map.put(".mseq","application/vnd.mseq");
        map.put(".pwn","application/vnd.3m.post-it-notes");
        map.put(".plb","application/vnd.3gpp.pic-bw-large");
        map.put(".psb","application/vnd.3gpp.pic-bw-small");
        map.put(".pvb","application/vnd.3gpp.pic-bw-var");
        map.put(".tcap","application/vnd.3gpp2.tcap");
        map.put(".7z","application/x-7z-compressed");
        map.put(".abw","application/x-abiword");
        map.put(".ace","application/x-ace-compressed");
        map.put(".acc","application/vnd.americandynamics.acc");
        map.put(".acu","application/vnd.acucobol");
        map.put(".atc","application/vnd.acucorp");
        map.put(".adp","audio/adpcm");
        map.put(".aab","application/x-authorware-bin");
        map.put(".aam","application/x-authorware-map");
        map.put(".aas","application/x-authorware-seg");
        map.put(".air","application/vnd.adobe.air-application-installer-package+zip");
        map.put(".swf","application/x-shockwave-flash");
        map.put(".fxp","application/vnd.adobe.fxp");
        map.put(".pdf","application/pdf");
        map.put(".ppd","application/vnd.cups-ppd");
        map.put(".dir","application/x-director");
        map.put(".xdp","application/vnd.adobe.xdp+xml");
        map.put(".xfdf","application/vnd.adobe.xfdf");
        map.put(".aac","audio/x-aac");
        map.put(".ahead","application/vnd.ahead.space");
        map.put(".azf","application/vnd.airzip.filesecure.azf");
        map.put(".azs","application/vnd.airzip.filesecure.azs");
        map.put(".azw","application/vnd.amazon.ebook");
        map.put(".ami","application/vnd.amiga.ami");
        map.put("N/A","application/andrew-inset");
        map.put(".apk","application/vnd.android.package-archive");
        map.put(".cii","application/vnd.anser-web-certificate-issue-initiation");
        map.put(".fti","application/vnd.anser-web-funds-transfer-initiation");
        map.put(".atx","application/vnd.antix.game-component");
        map.put(".mpkg","application/vnd.apple.installer+xml");
        map.put(".aw","application/applixware");
        map.put(".les","application/vnd.hhe.lesson-player");
        map.put(".swi","application/vnd.aristanetworks.swi");
        map.put(".s","text/x-asm");
        map.put(".atomcat","application/atomcat+xml");
        map.put(".atomsvc","application/atomsvc+xml");
        map.put(".xml","application/atom+xml");
        map.put(".atom","application/atom+xml");
        map.put(".ac","application/pkix-attr-cert");
        map.put(".aif","audio/x-aiff");
        map.put(".avi","video/x-msvideo");
        map.put(".aep","application/vnd.audiograph");
        map.put(".dxf","image/vnd.dxf");
        map.put(".dwf","model/vnd.dwf");
        map.put(".par","text/plain-bas");
        map.put(".bcpio","application/x-bcpio");
        map.put(".bin","application/octet-stream");
        map.put(".bmp","image/bmp");
        map.put(".torrent","application/x-bittorrent");
        map.put(".cod","application/vnd.rim.cod");
        map.put(".mpm","application/vnd.blueice.multipass");
        map.put(".bmi","application/vnd.bmi");
        map.put(".sh","application/x-sh");
        map.put(".btif","image/prs.btif");
        map.put(".rep","application/vnd.businessobjects");
        map.put(".bz","application/x-bzip");
        map.put(".bz2","application/x-bzip2");
        map.put(".csh","application/x-csh");
        map.put(".c","text/x-c");
        map.put(".cdxml","application/vnd.chemdraw+xml");
        map.put(".css","text/css");
        map.put(".cdx","chemical/x-cdx");
        map.put(".cml","chemical/x-cml");
        map.put(".csml","chemical/x-csml");
        map.put(".cdbcmsg","application/vnd.contact.cmsg");
        map.put(".cla","application/vnd.claymore");
        map.put(".c4g","application/vnd.clonk.c4group");
        map.put(".sub","image/vnd.dvb.subtitle");
        map.put(".cdmia","application/cdmi-capability");
        map.put(".cdmic","application/cdmi-container");
        map.put(".cdmid","application/cdmi-domain");
        map.put(".cdmio","application/cdmi-object");
        map.put(".cdmiq","application/cdmi-queue");
        map.put(".c11amc","application/vnd.cluetrust.cartomobile-config");
        map.put(".c11amz","application/vnd.cluetrust.cartomobile-config-pkg");
        map.put(".ras","image/x-cmu-raster");
        map.put(".dae","model/vnd.collada+xml");
        map.put(".csv","text/csv");
        map.put(".cpt","application/mac-compactpro");
        map.put(".wmlc","application/vnd.wap.wmlc");
        map.put(".cgm","image/cgm");
        map.put(".ice","x-conference/x-cooltalk");
        map.put(".cmx","image/x-cmx");
        map.put(".xar","application/vnd.xara");
        map.put(".cmc","application/vnd.cosmocaller");
        map.put(".cpio","application/x-cpio");
        map.put(".clkx","application/vnd.crick.clicker");
        map.put(".clkk","application/vnd.crick.clicker.keyboard");
        map.put(".clkp","application/vnd.crick.clicker.palette");
        map.put(".clkt","application/vnd.crick.clicker.template");
        map.put(".clkw","application/vnd.crick.clicker.wordbank");
        map.put(".wbs","application/vnd.criticaltools.wbs+xml");
        map.put(".cryptonote","application/vnd.rig.cryptonote");
        map.put(".cif","chemical/x-cif");
        map.put(".cmdf","chemical/x-cmdf");
        map.put(".cu","application/cu-seeme");
        map.put(".cww","application/prs.cww");
        map.put(".curl","text/vnd.curl");
        map.put(".dcurl","text/vnd.curl.dcurl");
        map.put(".mcurl","text/vnd.curl.mcurl");
        map.put(".scurl","text/vnd.curl.scurl");
        map.put(".car","application/vnd.curl.car");
        map.put(".pcurl","application/vnd.curl.pcurl");
        map.put(".cmp","application/vnd.yellowriver-custom-menu");
        map.put(".dssc","application/dssc+der");
        map.put(".xdssc","application/dssc+xml");
        map.put(".deb","application/x-debian-package");
        map.put(".uva","audio/vnd.dece.audio");
        map.put(".uvi","image/vnd.dece.graphic");
        map.put(".uvh","video/vnd.dece.hd");
        map.put(".uvm","video/vnd.dece.mobile");
        map.put(".uvu","video/vnd.uvvu.mp4");
        map.put(".uvp","video/vnd.dece.pd");
        map.put(".uvs","video/vnd.dece.sd");
        map.put(".uvv","video/vnd.dece.video");
        map.put(".dvi","application/x-dvi");
        map.put(".seed","application/vnd.fdsn.seed");
        map.put(".dtb","application/x-dtbook+xml");
        map.put(".res","application/x-dtbresource+xml");
        map.put(".ait","application/vnd.dvb.ait");
        map.put(".svc","application/vnd.dvb.service");
        map.put(".eol","audio/vnd.digital-winds");
        map.put(".djvu","image/vnd.djvu");
        map.put(".dtd","application/xml-dtd");
        map.put(".mlp","application/vnd.dolby.mlp");
        map.put(".wad","application/x-doom");
        map.put(".dpg","application/vnd.dpgraph");
        map.put(".dra","audio/vnd.dra");
        map.put(".dfac","application/vnd.dreamfactory");
        map.put(".dts","audio/vnd.dts");
        map.put(".dtshd","audio/vnd.dts.hd");
        map.put(".dwg","image/vnd.dwg");
        map.put(".geo","application/vnd.dynageo");
        map.put(".es","application/ecmascript");
        map.put(".mag","application/vnd.ecowin.chart");
        map.put(".mmr","image/vnd.fujixerox.edmics-mmr");
        map.put(".rlc","image/vnd.fujixerox.edmics-rlc");
        map.put(".exi","application/exi");
        map.put(".mgz","application/vnd.proteus.magazine");
        map.put(".epub","application/epub+zip");
        map.put(".eml","message/rfc822");
        map.put(".nml","application/vnd.enliven");
        map.put(".xpr","application/vnd.is-xpr");
        map.put(".xif","image/vnd.xiff");
        map.put(".xfdl","application/vnd.xfdl");
        map.put(".emma","application/emma+xml");
        map.put(".ez2","application/vnd.ezpix-album");
        map.put(".ez3","application/vnd.ezpix-package");
        map.put(".fst","image/vnd.fst");
        map.put(".fvt","video/vnd.fvt");
        map.put(".fbs","image/vnd.fastbidsheet");
        map.put(".fe_launch","application/vnd.denovo.fcselayout-link");
        map.put(".f4v","video/x-f4v");
        map.put(".flv","video/x-flv");
        map.put(".fpx","image/vnd.fpx");
        map.put(".npx","image/vnd.net-fpx");
        map.put(".flx","text/vnd.fmi.flexstor");
        map.put(".fli","video/x-fli");
        map.put(".ftc","application/vnd.fluxtime.clip");
        map.put(".fdf","application/vnd.fdf");
        map.put(".f","text/x-fortran");
        map.put(".mif","application/vnd.mif");
        map.put(".fm","application/vnd.framemaker");
        map.put(".fh","image/x-freehand");
        map.put(".fsc","application/vnd.fsc.weblaunch");
        map.put(".fnc","application/vnd.frogans.fnc");
        map.put(".ltf","application/vnd.frogans.ltf");
        map.put(".ddd","application/vnd.fujixerox.ddd");
        map.put(".xdw","application/vnd.fujixerox.docuworks");
        map.put(".xbd","application/vnd.fujixerox.docuworks.binder");
        map.put(".oas","application/vnd.fujitsu.oasys");
        map.put(".oa2","application/vnd.fujitsu.oasys2");
        map.put(".oa3","application/vnd.fujitsu.oasys3");
        map.put(".fg5","application/vnd.fujitsu.oasysgp");
        map.put(".bh2","application/vnd.fujitsu.oasysprs");
        map.put(".spl","application/x-futuresplash");
        map.put(".fzs","application/vnd.fuzzysheet");
        map.put(".g3","image/g3fax");
        map.put(".gmx","application/vnd.gmx");
        map.put(".gtw","model/vnd.gtw");
        map.put(".txd","application/vnd.genomatix.tuxedo");
        map.put(".ggb","application/vnd.geogebra.file");
        map.put(".ggt","application/vnd.geogebra.tool");
        map.put(".gdl","model/vnd.gdl");
        map.put(".gex","application/vnd.geometry-explorer");
        map.put(".gxt","application/vnd.geonext");
        map.put(".g2w","application/vnd.geoplan");
        map.put(".g3w","application/vnd.geospace");
        map.put(".gsf","application/x-font-ghostscript");
        map.put(".bdf","application/x-font-bdf");
        map.put(".gtar","application/x-gtar");
        map.put(".texinfo","application/x-texinfo");
        map.put(".gnumeric","application/x-gnumeric");
        map.put(".kml","application/vnd.google-earth.kml+xml");
        map.put(".kmz","application/vnd.google-earth.kmz");
        map.put(".gqf","application/vnd.grafeq");
        map.put(".gif","image/gif");
        map.put(".gv","text/vnd.graphviz");
        map.put(".gac","application/vnd.groove-account");
        map.put(".ghf","application/vnd.groove-help");
        map.put(".gim","application/vnd.groove-identity-message");
        map.put(".grv","application/vnd.groove-injector");
        map.put(".gtm","application/vnd.groove-tool-message");
        map.put(".tpl","application/vnd.groove-tool-template");
        map.put(".vcg","application/vnd.groove-vcard");
        map.put(".h261","video/h261");
        map.put(".h263","video/h263");
        map.put(".h264","video/h264");
        map.put(".hpid","application/vnd.hp-hpid");
        map.put(".hps","application/vnd.hp-hps");
        map.put(".hdf","application/x-hdf");
        map.put(".rip","audio/vnd.rip");
        map.put(".hbci","application/vnd.hbci");
        map.put(".jlt","application/vnd.hp-jlyt");
        map.put(".pcl","application/vnd.hp-pcl");
        map.put(".hpgl","application/vnd.hp-hpgl");
        map.put(".hvs","application/vnd.yamaha.hv-script");
        map.put(".hvd","application/vnd.yamaha.hv-dic");
        map.put(".hvp","application/vnd.yamaha.hv-voice");
        map.put(".sfd-hdstx","application/vnd.hydrostatix.sof-data");
        map.put(".stk","application/hyperstudio");
        map.put(".hal","application/vnd.hal+xml");
        map.put(".html","text/html");
        map.put(".irm","application/vnd.ibm.rights-management");
        map.put(".sc","application/vnd.ibm.secure-container");
        map.put(".ics","text/calendar");
        map.put(".icc","application/vnd.iccprofile");
        map.put(".ico","image/x-icon");
        map.put(".igl","application/vnd.igloader");
        map.put(".ief","image/ief");
        map.put(".ivp","application/vnd.immervision-ivp");
        map.put(".ivu","application/vnd.immervision-ivu");
        map.put(".rif","application/reginfo+xml");
        map.put(".3dml","text/vnd.in3d.3dml");
        map.put(".spot","text/vnd.in3d.spot");
        map.put(".igs","model/iges");
        map.put(".i2g","application/vnd.intergeo");
        map.put(".cdy","application/vnd.cinderella");
        map.put(".xpw","application/vnd.intercon.formnet");
        map.put(".fcs","application/vnd.isac.fcs");
        map.put(".ipfix","application/ipfix");
        map.put(".cer","application/pkix-cert");
        map.put(".pki","application/pkixcmp");
        map.put(".crl","application/pkix-crl");
        map.put(".pkipath","application/pkix-pkipath");
        map.put(".igm","application/vnd.insors.igm");
        map.put(".rcprofile","application/vnd.ipunplugged.rcprofile");
        map.put(".irp","application/vnd.irepository.package+xml");
        map.put(".jad","text/vnd.sun.j2me.app-descriptor");
        map.put(".jar","application/java-archive");
        map.put(".class","application/java-vm");
        map.put(".jnlp","application/x-java-jnlp-file");
        map.put(".ser","application/java-serialized-object");
        map.put(".java","text/x-java-source,java");
        map.put(".js","application/javascript");
        map.put(".json","application/json");
        map.put(".joda","application/vnd.joost.joda-archive");
        map.put(".jpm","video/jpm");
        map.put(".jpeg","image/jpeg");
        map.put(".jpg","image/jpeg");
        map.put(".jpg","image/x-citrix-jpeg");
        map.put(".jpeg","image/x-citrix-jpeg");
        map.put(".pjpeg","image/pjpeg");
        map.put(".jpgv","video/jpeg");
        map.put(".ktz","application/vnd.kahootz");
        map.put(".mmd","application/vnd.chipnuts.karaoke-mmd");
        map.put(".karbon","application/vnd.kde.karbon");
        map.put(".chrt","application/vnd.kde.kchart");
        map.put(".kfo","application/vnd.kde.kformula");
        map.put(".flw","application/vnd.kde.kivio");
        map.put(".kon","application/vnd.kde.kontour");
        map.put(".kpr","application/vnd.kde.kpresenter");
        map.put(".ksp","application/vnd.kde.kspread");
        map.put(".kwd","application/vnd.kde.kword");
        map.put(".htke","application/vnd.kenameaapp");
        map.put(".kia","application/vnd.kidspiration");
        map.put(".kne","application/vnd.kinar");
        map.put(".sse","application/vnd.kodak-descriptor");
        map.put(".lasxml","application/vnd.las.las+xml");
        map.put(".latex","application/x-latex");
        map.put(".lbd","application/vnd.llamagraphics.life-balance.desktop");
        map.put(".lbe","application/vnd.llamagraphics.life-balance.exchange+xml");
        map.put(".jam","application/vnd.jam");
        map.put("0.123","application/vnd.lotus-1-2-3");
        map.put(".apr","application/vnd.lotus-approach");
        map.put(".pre","application/vnd.lotus-freelance");
        map.put(".nsf","application/vnd.lotus-notes");
        map.put(".org","application/vnd.lotus-organizer");
        map.put(".scm","application/vnd.lotus-screencam");
        map.put(".lwp","application/vnd.lotus-wordpro");
        map.put(".lvp","audio/vnd.lucent.voice");
        map.put(".m3u","audio/x-mpegurl");
        map.put(".m4v","video/x-m4v");
        map.put(".hqx","application/mac-binhex40");
        map.put(".portpkg","application/vnd.macports.portpkg");
        map.put(".mgp","application/vnd.osgeo.mapguide.package");
        map.put(".mrc","application/marc");
        map.put(".mrcx","application/marcxml+xml");
        map.put(".mxf","application/mxf");
        map.put(".nbp","application/vnd.wolfram.player");
        map.put(".ma","application/mathematica");
        map.put(".mathml","application/mathml+xml");
        map.put(".mbox","application/mbox");
        map.put(".mc1","application/vnd.medcalcdata");
        map.put(".mscml","application/mediaservercontrol+xml");
        map.put(".cdkey","application/vnd.mediastation.cdkey");
        map.put(".mwf","application/vnd.mfer");
        map.put(".mfm","application/vnd.mfmp");
        map.put(".msh","model/mesh");
        map.put(".mads","application/mads+xml");
        map.put(".mets","application/mets+xml");
        map.put(".mods","application/mods+xml");
        map.put(".meta4","application/metalink4+xml");
        map.put(".mcd","application/vnd.mcd");
        map.put(".flo","application/vnd.micrografx.flo");
        map.put(".igx","application/vnd.micrografx.igx");
        map.put(".es3","application/vnd.eszigno3+xml");
        map.put(".mdb","application/x-msaccess");
        map.put(".asf","video/x-ms-asf");
        map.put(".exe","application/x-msdownload");
        map.put(".cil","application/vnd.ms-artgalry");
        map.put(".cab","application/vnd.ms-cab-compressed");
        map.put(".ims","application/vnd.ms-ims");
        map.put(".application","application/x-ms-application");
        map.put(".clp","application/x-msclip");
        map.put(".mdi","image/vnd.ms-modi");
        map.put(".eot","application/vnd.ms-fontobject");
        map.put(".xls","application/vnd.ms-excel");
        map.put(".xlam","application/vnd.ms-excel.addin.macroenabled.12");
        map.put(".xlsb","application/vnd.ms-excel.sheet.binary.macroenabled.12");
        map.put(".xltm","application/vnd.ms-excel.template.macroenabled.12");
        map.put(".xlsm","application/vnd.ms-excel.sheet.macroenabled.12");
        map.put(".chm","application/vnd.ms-htmlhelp");
        map.put(".crd","application/x-mscardfile");
        map.put(".lrm","application/vnd.ms-lrm");
        map.put(".mvb","application/x-msmediaview");
        map.put(".mny","application/x-msmoney");
        map.put(".pptx","application/vnd.openxmlformats-officedocument.presentationml.presentation");
        map.put(".sldx","application/vnd.openxmlformats-officedocument.presentationml.slide");
        map.put(".ppsx","application/vnd.openxmlformats-officedocument.presentationml.slideshow");
        map.put(".potx","application/vnd.openxmlformats-officedocument.presentationml.template");
        map.put(".xlsx","application/vnd.openxmlformats-officedocument.spreadsheetml.sheet");
        map.put(".xltx","application/vnd.openxmlformats-officedocument.spreadsheetml.template");
        map.put(".docx","application/vnd.openxmlformats-officedocument.wordprocessingml.document");
        map.put(".dotx","application/vnd.openxmlformats-officedocument.wordprocessingml.template");
        map.put(".obd","application/x-msbinder");
        map.put(".thmx","application/vnd.ms-officetheme");
        map.put(".onetoc","application/onenote");
        map.put(".pya","audio/vnd.ms-playready.media.pya");
        map.put(".pyv","video/vnd.ms-playready.media.pyv");
        map.put(".ppt","application/vnd.ms-powerpoint");
        map.put(".ppam","application/vnd.ms-powerpoint.addin.macroenabled.12");
        map.put(".sldm","application/vnd.ms-powerpoint.slide.macroenabled.12");
        map.put(".pptm","application/vnd.ms-powerpoint.presentation.macroenabled.12");
        map.put(".ppsm","application/vnd.ms-powerpoint.slideshow.macroenabled.12");
        map.put(".potm","application/vnd.ms-powerpoint.template.macroenabled.12");
        map.put(".mpp","application/vnd.ms-project");
        map.put(".pub","application/x-mspublisher");
        map.put(".scd","application/x-msschedule");
        map.put(".xap","application/x-silverlight-app");
        map.put(".stl","application/vnd.ms-pki.stl");
        map.put(".cat","application/vnd.ms-pki.seccat");
        map.put(".vsd","application/vnd.visio");
        map.put(".vsdx","application/vnd.visio2013");
        map.put(".wm","video/x-ms-wm");
        map.put(".wma","audio/x-ms-wma");
        map.put(".wax","audio/x-ms-wax");
        map.put(".wmx","video/x-ms-wmx");
        map.put(".wmd","application/x-ms-wmd");
        map.put(".wpl","application/vnd.ms-wpl");
        map.put(".wmz","application/x-ms-wmz");
        map.put(".wmv","video/x-ms-wmv");
        map.put(".wvx","video/x-ms-wvx");
        map.put(".wmf","application/x-msmetafile");
        map.put(".trm","application/x-msterminal");
        map.put(".doc","application/msword");
        map.put(".docm","application/vnd.ms-word.document.macroenabled.12");
        map.put(".dotm","application/vnd.ms-word.template.macroenabled.12");
        map.put(".wri","application/x-mswrite");
        map.put(".wps","application/vnd.ms-works");
        map.put(".xbap","application/x-ms-xbap");
        map.put(".xps","application/vnd.ms-xpsdocument");
        map.put(".mid","audio/midi");
        map.put(".mpy","application/vnd.ibm.minipay");
        map.put(".afp","application/vnd.ibm.modcap");
        map.put(".rms","application/vnd.jcp.javame.midlet-rms");
        map.put(".tmo","application/vnd.tmobile-livetv");
        map.put(".prc","application/x-mobipocket-ebook");
        map.put(".mbk","application/vnd.mobius.mbk");
        map.put(".dis","application/vnd.mobius.dis");
        map.put(".plc","application/vnd.mobius.plc");
        map.put(".mqy","application/vnd.mobius.mqy");
        map.put(".msl","application/vnd.mobius.msl");
        map.put(".txf","application/vnd.mobius.txf");
        map.put(".daf","application/vnd.mobius.daf");
        map.put(".fly","text/vnd.fly");
        map.put(".mpc","application/vnd.mophun.certificate");
        map.put(".mpn","application/vnd.mophun.application");
        map.put(".mj2","video/mj2");
        map.put(".mpga","audio/mpeg");
        map.put(".mxu","video/vnd.mpegurl");
        map.put(".mpeg","video/mpeg");
        map.put(".m21","application/mp21");
        map.put(".mp4a","audio/mp4");
        map.put(".mp4","video/mp4");
        map.put(".mp4","application/mp4");
        map.put(".m3u8","application/vnd.apple.mpegurl");
        map.put(".mus","application/vnd.musician");
        map.put(".msty","application/vnd.muvee.style");
        map.put(".mxml","application/xv+xml");
        map.put(".ngdat","application/vnd.nokia.n-gage.data");
        map.put(".n-gage","application/vnd.nokia.n-gage.symbian.install");
        map.put(".ncx","application/x-dtbncx+xml");
        map.put(".nc","application/x-netcdf");
        map.put(".nlu","application/vnd.neurolanguage.nlu");
        map.put(".dna","application/vnd.dna");
        map.put(".nnd","application/vnd.noblenet-directory");
        map.put(".nns","application/vnd.noblenet-sealer");
        map.put(".nnw","application/vnd.noblenet-web");
        map.put(".rpst","application/vnd.nokia.radio-preset");
        map.put(".rpss","application/vnd.nokia.radio-presets");
        map.put(".n3","text/n3");
        map.put(".edm","application/vnd.novadigm.edm");
        map.put(".edx","application/vnd.novadigm.edx");
        map.put(".ext","application/vnd.novadigm.ext");
        map.put(".gph","application/vnd.flographit");
        map.put(".ecelp4800","audio/vnd.nuera.ecelp4800");
        map.put(".ecelp7470","audio/vnd.nuera.ecelp7470");
        map.put(".ecelp9600","audio/vnd.nuera.ecelp9600");
        map.put(".oda","application/oda");
        map.put(".ogx","application/ogg");
        map.put(".oga","audio/ogg");
        map.put(".ogv","video/ogg");
        map.put(".dd2","application/vnd.oma.dd2+xml");
        map.put(".oth","application/vnd.oasis.opendocument.text-web");
        map.put(".opf","application/oebps-package+xml");
        map.put(".qbo","application/vnd.intu.qbo");
        map.put(".oxt","application/vnd.openofficeorg.extension");
        map.put(".osf","application/vnd.yamaha.openscoreformat");
        map.put(".weba","audio/webm");
        map.put(".webm","video/webm");
        map.put(".odc","application/vnd.oasis.opendocument.chart");
        map.put(".otc","application/vnd.oasis.opendocument.chart-template");
        map.put(".odb","application/vnd.oasis.opendocument.database");
        map.put(".odf","application/vnd.oasis.opendocument.formula");
        map.put(".odft","application/vnd.oasis.opendocument.formula-template");
        map.put(".odg","application/vnd.oasis.opendocument.graphics");
        map.put(".otg","application/vnd.oasis.opendocument.graphics-template");
        map.put(".odi","application/vnd.oasis.opendocument.image");
        map.put(".oti","application/vnd.oasis.opendocument.image-template");
        map.put(".odp","application/vnd.oasis.opendocument.presentation");
        map.put(".otp","application/vnd.oasis.opendocument.presentation-template");
        map.put(".ods","application/vnd.oasis.opendocument.spreadsheet");
        map.put(".ots","application/vnd.oasis.opendocument.spreadsheet-template");
        map.put(".odt","application/vnd.oasis.opendocument.text");
        map.put(".odm","application/vnd.oasis.opendocument.text-master");
        map.put(".ott","application/vnd.oasis.opendocument.text-template");
        map.put(".ktx","image/ktx");
        map.put(".sxc","application/vnd.sun.xml.calc");
        map.put(".stc","application/vnd.sun.xml.calc.template");
        map.put(".sxd","application/vnd.sun.xml.draw");
        map.put(".std","application/vnd.sun.xml.draw.template");
        map.put(".sxi","application/vnd.sun.xml.impress");
        map.put(".sti","application/vnd.sun.xml.impress.template");
        map.put(".sxm","application/vnd.sun.xml.math");
        map.put(".sxw","application/vnd.sun.xml.writer");
        map.put(".sxg","application/vnd.sun.xml.writer.global");
        map.put(".stw","application/vnd.sun.xml.writer.template");
        map.put(".otf","application/x-font-otf");
        map.put(".osfpvg","application/vnd.yamaha.openscoreformat.osfpvg+xml");
        map.put(".dp","application/vnd.osgi.dp");
        map.put(".pdb","application/vnd.palm");
        map.put(".p","text/x-pascal");
        map.put(".paw","application/vnd.pawaafile");
        map.put(".pclxl","application/vnd.hp-pclxl");
        map.put(".efif","application/vnd.picsel");
        map.put(".pcx","image/x-pcx");
        map.put(".psd","image/vnd.adobe.photoshop");
        map.put(".prf","application/pics-rules");
        map.put(".pic","image/x-pict");
        map.put(".chat","application/x-chat");
        map.put(".p10","application/pkcs10");
        map.put(".p12","application/x-pkcs12");
        map.put(".p7m","application/pkcs7-mime");
        map.put(".p7s","application/pkcs7-signature");
        map.put(".p7r","application/x-pkcs7-certreqresp");
        map.put(".p7b","application/x-pkcs7-certificates");
        map.put(".p8","application/pkcs8");
        map.put(".plf","application/vnd.pocketlearn");
        map.put(".pnm","image/x-portable-anymap");
        map.put(".pbm","image/x-portable-bitmap");
        map.put(".pcf","application/x-font-pcf");
        map.put(".pfr","application/font-tdpfr");
        map.put(".pgn","application/x-chess-pgn");
        map.put(".pgm","image/x-portable-graymap");
        map.put(".png","image/png");
        map.put(".png","image/x-citrix-png");
        map.put(".png","image/x-png");
        map.put(".ppm","image/x-portable-pixmap");
        map.put(".pskcxml","application/pskc+xml");
        map.put(".pml","application/vnd.ctc-posml");
        map.put(".ai","application/postscript");
        map.put(".pfa","application/x-font-type1");
        map.put(".pbd","application/vnd.powerbuilder6");
        map.put(".pgp","application/pgp-encrypted");
        map.put(".pgp","application/pgp-signature");
        map.put(".box","application/vnd.previewsystems.box");
        map.put(".ptid","application/vnd.pvi.ptid1");
        map.put(".pls","application/pls+xml");
        map.put(".str","application/vnd.pg.format");
        map.put(".ei6","application/vnd.pg.osasli");
        map.put(".dsc","text/prs.lines.tag");
        map.put(".psf","application/x-font-linux-psf");
        map.put(".qps","application/vnd.publishare-delta-tree");
        map.put(".wg","application/vnd.pmi.widget");
        map.put(".qxd","application/vnd.quark.quarkxpress");
        map.put(".esf","application/vnd.epson.esf");
        map.put(".msf","application/vnd.epson.msf");
        map.put(".ssf","application/vnd.epson.ssf");
        map.put(".qam","application/vnd.epson.quickanime");
        map.put(".qfx","application/vnd.intu.qfx");
        map.put(".qt","video/quicktime");
        map.put(".rar","application/x-rar-compressed");
        map.put(".ram","audio/x-pn-realaudio");
        map.put(".rmp","audio/x-pn-realaudio-plugin");
        map.put(".rsd","application/rsd+xml");
        map.put(".rm","application/vnd.rn-realmedia");
        map.put(".bed","application/vnd.realvnc.bed");
        map.put(".mxl","application/vnd.recordare.musicxml");
        map.put(".musicxml","application/vnd.recordare.musicxml+xml");
        map.put(".rnc","application/relax-ng-compact-syntax");
        map.put(".rdz","application/vnd.data-vision.rdz");
        map.put(".rdf","application/rdf+xml");
        map.put(".rp9","application/vnd.cloanto.rp9");
        map.put(".jisp","application/vnd.jisp");
        map.put(".rtf","application/rtf");
        map.put(".rtx","text/richtext");
        map.put(".link66","application/vnd.route66.link66+xml");
        map.put(".rss","application/rss+xml");
        map.put(".xml","application/rss+xml");
        map.put(".shf","application/shf+xml");
        map.put(".st","application/vnd.sailingtracker.track");
        map.put(".svg","image/svg+xml");
        map.put(".sus","application/vnd.sus-calendar");
        map.put(".sru","application/sru+xml");
        map.put(".setpay","application/set-payment-initiation");
        map.put(".setreg","application/set-registration-initiation");
        map.put(".sema","application/vnd.sema");
        map.put(".semd","application/vnd.semd");
        map.put(".semf","application/vnd.semf");
        map.put(".see","application/vnd.seemail");
        map.put(".snf","application/x-font-snf");
        map.put(".spq","application/scvp-vp-request");
        map.put(".spp","application/scvp-vp-response");
        map.put(".scq","application/scvp-cv-request");
        map.put(".scs","application/scvp-cv-response");
        map.put(".sdp","application/sdp");
        map.put(".etx","text/x-setext");
        map.put(".movie","video/x-sgi-movie");
        map.put(".ifm","application/vnd.shana.informed.formdata");
        map.put(".itp","application/vnd.shana.informed.formtemplate");
        map.put(".iif","application/vnd.shana.informed.interchange");
        map.put(".ipk","application/vnd.shana.informed.package");
        map.put(".tfi","application/thraud+xml");
        map.put(".shar","application/x-shar");
        map.put(".rgb","image/x-rgb");
        map.put(".slt","application/vnd.epson.salt");
        map.put(".aso","application/vnd.accpac.simply.aso");
        map.put(".imp","application/vnd.accpac.simply.imp");
        map.put(".twd","application/vnd.simtech-mindmapper");
        map.put(".csp","application/vnd.commonspace");
        map.put(".saf","application/vnd.yamaha.smaf-audio");
        map.put(".mmf","application/vnd.smaf");
        map.put(".spf","application/vnd.yamaha.smaf-phrase");
        map.put(".teacher","application/vnd.smart.teacher");
        map.put(".svd","application/vnd.svd");
        map.put(".rq","application/sparql-query");
        map.put(".srx","application/sparql-results+xml");
        map.put(".gram","application/srgs");
        map.put(".grxml","application/srgs+xml");
        map.put(".ssml","application/ssml+xml");
        map.put(".skp","application/vnd.koan");
        map.put(".sgml","text/sgml");
        map.put(".sdc","application/vnd.stardivision.calc");
        map.put(".sda","application/vnd.stardivision.draw");
        map.put(".sdd","application/vnd.stardivision.impress");
        map.put(".smf","application/vnd.stardivision.math");
        map.put(".sdw","application/vnd.stardivision.writer");
        map.put(".sgl","application/vnd.stardivision.writer-global");
        map.put(".sm","application/vnd.stepmania.stepchart");
        map.put(".sit","application/x-stuffit");
        map.put(".sitx","application/x-stuffitx");
        map.put(".sdkm","application/vnd.solent.sdkm+xml");
        map.put(".xo","application/vnd.olpc-sugar");
        map.put(".au","audio/basic");
        map.put(".wqd","application/vnd.wqd");
        map.put(".sis","application/vnd.symbian.install");
        map.put(".smi","application/smil+xml");
        map.put(".xsm","application/vnd.syncml+xml");
        map.put(".bdm","application/vnd.syncml.dm+wbxml");
        map.put(".xdm","application/vnd.syncml.dm+xml");
        map.put(".sv4cpio","application/x-sv4cpio");
        map.put(".sv4crc","application/x-sv4crc");
        map.put(".sbml","application/sbml+xml");
        map.put(".tsv","text/tab-separated-values");
        map.put(".tiff","image/tiff");
        map.put(".tao","application/vnd.tao.intent-module-archive");
        map.put(".tar","application/x-tar");
        map.put(".tcl","application/x-tcl");
        map.put(".tex","application/x-tex");
        map.put(".tfm","application/x-tex-tfm");
        map.put(".tei","application/tei+xml");
        map.put(".txt","text/plain");
        map.put(".dxp","application/vnd.spotfire.dxp");
        map.put(".sfs","application/vnd.spotfire.sfs");
        map.put(".tsd","application/timestamped-data");
        map.put(".tpt","application/vnd.trid.tpt");
        map.put(".mxs","application/vnd.triscape.mxs");
        map.put(".t","text/troff");
        map.put(".tra","application/vnd.trueapp");
        map.put(".ttf","application/x-font-ttf");
        map.put(".ttl","text/turtle");
        map.put(".umj","application/vnd.umajin");
        map.put(".uoml","application/vnd.uoml+xml");
        map.put(".unityweb","application/vnd.unity");
        map.put(".ufd","application/vnd.ufdl");
        map.put(".uri","text/uri-list");
        map.put(".utz","application/vnd.uiq.theme");
        map.put(".ustar","application/x-ustar");
        map.put(".uu","text/x-uuencode");
        map.put(".vcs","text/x-vcalendar");
        map.put(".vcf","text/x-vcard");
        map.put(".vcd","application/x-cdlink");
        map.put(".vsf","application/vnd.vsf");
        map.put(".wrl","model/vrml");
        map.put(".vcx","application/vnd.vcx");
        map.put(".mts","model/vnd.mts");
        map.put(".vtu","model/vnd.vtu");
        map.put(".vis","application/vnd.visionary");
        map.put(".viv","video/vnd.vivo");
        map.put(".ccxml","application/ccxml+xml,");
        map.put(".vxml","application/voicexml+xml");
        map.put(".src","application/x-wais-source");
        map.put(".wbxml","application/vnd.wap.wbxml");
        map.put(".wbmp","image/vnd.wap.wbmp");
        map.put(".wav","audio/x-wav");
        map.put(".davmount","application/davmount+xml");
        map.put(".woff","application/x-font-woff");
        map.put(".wspolicy","application/wspolicy+xml");
        map.put(".webp","image/webp");
        map.put(".wtb","application/vnd.webturbo");
        map.put(".wgt","application/widget");
        map.put(".hlp","application/winhlp");
        map.put(".wml","text/vnd.wap.wml");
        map.put(".wmls","text/vnd.wap.wmlscript");
        map.put(".wmlsc","application/vnd.wap.wmlscriptc");
        map.put(".wpd","application/vnd.wordperfect");
        map.put(".stf","application/vnd.wt.stf");
        map.put(".wsdl","application/wsdl+xml");
        map.put(".xbm","image/x-xbitmap");
        map.put(".xpm","image/x-xpixmap");
        map.put(".xwd","image/x-xwindowdump");
        map.put(".der","application/x-x509-ca-cert");
        map.put(".fig","application/x-xfig");
        map.put(".xhtml","application/xhtml+xml");
        map.put(".xml","application/xml");
        map.put(".xdf","application/xcap-diff+xml");
        map.put(".xenc","application/xenc+xml");
        map.put(".xer","application/patch-ops-error+xml");
        map.put(".rl","application/resource-lists+xml");
        map.put(".rs","application/rls-services+xml");
        map.put(".rld","application/resource-lists-diff+xml");
        map.put(".xslt","application/xslt+xml");
        map.put(".xop","application/xop+xml");
        map.put(".xpi","application/x-xpinstall");
        map.put(".xspf","application/xspf+xml");
        map.put(".xul","application/vnd.mozilla.xul+xml");
        map.put(".xyz","chemical/x-xyz");
        map.put(".yaml","text/yaml");
        map.put(".yang","application/yang");
        map.put(".yin","application/yin+xml");
        map.put(".zir","application/vnd.zul");
        map.put(".zip","application/zip");
        map.put(".zmm","application/vnd.handheld-entertainment+xml");
        map.put(".zaz","application/vnd.zzazz.deck+xml");
        return map.get("."+fileExt.toLowerCase());
    }

    public void sendMailWithAttachment(String from,List<String> toList, String subject ,String body,String filePath, String filePath2) throws MessagingException{
        Properties props = new Properties();
        props.put("mail.smtp.host", "exchange.daralshifa.com");//
        props.put("mail.smtp.user", "ithelpdesk");
        props.put("mail.smtp.password", "it1234"); //mail.smtp.ssl.enable
        props.put("mail.smtp.ssl.enable", "false");
        Session session = Session.getDefaultInstance(props, null);
        session.setDebug(true);
        Message msg = new MimeMessage(session);
        msg.setFrom(new InternetAddress(from));
        InternetAddress ia=null;
        List<InternetAddress> addresees=new ArrayList<InternetAddress>();
        for(String to :toList ){
            ia=new InternetAddress(to);
            addresees.add(ia);
        }
        InternetAddress[] array = new InternetAddress[addresees.size()];
        array=addresees.toArray(array);

        msg.setRecipients(Message.RecipientType.TO,array);
        msg.setSubject(subject);
        msg.setText(body);
        MimeBodyPart attachmentBodyPart = new MimeBodyPart();
        File file=new File(filePath);
        MimeBodyPart attachmentBodyPart2 = new MimeBodyPart();
        DataSource source = new FileDataSource(file);
        attachmentBodyPart.setDataHandler(new DataHandler(source));
        attachmentBodyPart.setFileName(file.getName());








        Multipart multipart = new MimeMultipart();

        BodyPart messageBodyPart = new MimeBodyPart();
        // Fill the message
        messageBodyPart.setText(body);
        messageBodyPart.setContent(body, "text/html");

        multipart.addBodyPart(messageBodyPart);
        multipart.addBodyPart(attachmentBodyPart);

        if(filePath2!=null&&!filePath2.equals("")){
            File file2=new File(filePath2);
            DataSource source2 = new FileDataSource(file2);
            attachmentBodyPart2.setDataHandler(new DataHandler(source2));
            attachmentBodyPart2.setFileName(file2.getName());
            multipart.addBodyPart(attachmentBodyPart2);
        }
        msg.setContent(multipart);
        Transport.send(msg);
    }

}
